### ISSUE TITLE
更改generate_pdf.js里面路径的文件名，重新运行gulp，生成的pdf文件名未变

### ISSUE THREAD

**Issue by BakerLees** [Lxxyx/LxxyxResume#3]
## 第一步
![first](https://user-images.githubusercontent.com/16957726/34642629-3621f99e-f351-11e7-8d40-f19d1c7c64aa.png)

## 第二步
![second](https://user-images.githubusercontent.com/16957726/34642623-209d844e-f351-11e7-85de-2836d1ee123b.png)
生成的dist文件里面pdf文件名称未变化
![third](https://user-images.githubusercontent.com/16957726/34642640-87daf6fa-f351-11e7-9097-305d89a6b8c8.png)

更改`info.json`里面的内容，重新编译后端口`9000`的页面内容发生变化，但是并不能生成更改文件名后的`pdf`文件，请问这是为啥

**Comment by Lxxyx** [comment]
使用 gulp pdf 命令生成新的PDF
