### ISSUE TITLE
提一个小bug，及解决方法

### ISSUE THREAD

**Issue by fuchengjx** [Lxxyx/LxxyxResume#7]
开发环境： window 64位
window环境下npm run pdf   dist文件夹生成的简历应该是没有字体图标的 这里提出一个解决方法 npm run pdf后浏览器访问http://localhost:9001 那里生成的是完整的简历，然后用浏览器打印出来(以google浏览器为例  打印时应该勾选 背景图形 再打印） 然后就能打印出有字体图标的简历。

**Comment by Lxxyx** [comment]
可以提个 PR 哈~

**Comment by hoochanlon** [comment]
顺便增加一些可选项，例如：微信、微博等，可直接在JSON里省略，再发布。也许可操控度会更好

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hoochanlon** [comment]
谢谢你的好建议，方案已采纳；对了，我发起了新的PR，修正了我的一些安装方法上的疏漏及错误，以及增加较为简便和快速的安装方式。
